version: '3'
services:
  go-web-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=dev.gosocks.co.uk
      - LETSENCRYPT_HOST=dev.gosocks.co.uk